/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.detail_pembelian;
import entity.produk;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.detailPembelianServ;
import service.pembelianServ;
import service.produkServ;
import static view.FormLookup.kodeProdukDipilih;

/**
 *
 * @author buildAccount
 */
public class FormPembelian extends javax.swing.JFrame {

    produkServ aserv = new produkServ();
    detailPembelianServ serv = new detailPembelianServ();
    private String idPembelianGlobal = null; // disimpan 1x per transaksi
    int rowYangDipilih = -1;
   private int counterDetail = -1;


    /**
     * Creates new form FormPembelian
     */
    public FormPembelian() {
        initComponents();
        kondisiAwal();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnTambah1 = new javax.swing.JButton();
        btnTambah2 = new javax.swing.JButton();
        txtKeterangan = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtTotal = new javax.swing.JLabel();
        rbBarangDagang = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        rbOperasional = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        BtnLookup = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembelian = new javax.swing.JTable();
        txtNamaKeperluan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Harga");

        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });

        jLabel4.setText("Keterangan");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Input Pembelian/Pengeluaran");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Subtotal");

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pembelian/Pengeluaran");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(241, 241, 241))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Pembelian");

        btnTambah1.setBackground(new java.awt.Color(153, 51, 0));
        btnTambah1.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah1.setText("Hapus");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        btnTambah2.setBackground(new java.awt.Color(0, 102, 102));
        btnTambah2.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah2.setText("Tambah");
        btnTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah2ActionPerformed(evt);
            }
        });

        txtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganActionPerformed(evt);
            }
        });

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtTotal.setText("0");

        buttonGroup1.add(rbBarangDagang);
        rbBarangDagang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbBarangDagang.setText("Barang Dagang");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Jumlah x Harga");

        btnSimpan.setBackground(new java.awt.Color(0, 102, 102));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbOperasional);
        rbOperasional.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbOperasional.setText("Operasional");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(175, 584));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Dashboard");
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 102, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Data Produk");
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Penjualan");
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Pembelian");
        jButton8.setContentAreaFilled(false);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Rekap");
        jButton9.setContentAreaFilled(false);
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 102, 102));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Logout");
        jButton10.setContentAreaFilled(false);
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(13, 13, 13)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        BtnLookup.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BtnLookup.setText("Pilih Barang");
        BtnLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLookupActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Daftar Pembelian");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Keperluan");

        tblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembelian);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Jumlah");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Nama Barang/");

        jLabel12.setText("Tanggal");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Rp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel12)
                        .addGap(73, 73, 73)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(548, 548, 548)
                        .addComponent(btnTambah1)
                        .addGap(13, 13, 13)
                        .addComponent(btnTambah2))
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13)
                        .addGap(7, 7, 7)
                        .addComponent(txtTotal)
                        .addGap(583, 583, 583)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNamaKeperluan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(BtnLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel9))))
                                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15)
                                .addComponent(rbBarangDagang, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(rbOperasional)
                                .addGap(121, 121, 121)
                                .addComponent(jLabel7)
                                .addGap(37, 37, 37)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(rbBarangDagang)
                            .addComponent(rbOperasional)
                            .addComponent(jLabel7)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNamaKeperluan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnLookup)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel9)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTambah1)
                            .addComponent(btnTambah2))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10)
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTotal)
                                .addComponent(btnSimpan))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaKeyTyped

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
DefaultTableModel model = (DefaultTableModel) tblPembelian.getModel();

    int row = tblPembelian.getSelectedRow();

    // 1. pastikan ada baris yang dipilih
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
        return;
    }

    // 2. konfirmasi
    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus item ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi != JOptionPane.YES_OPTION) {
        return;
    }

    // 3. hapus dari JTable
    model.removeRow(row);

    // 4. hitung ulang total
    hitungTotal();

    // 5. reset mode edit
    rowYangDipilih = -1;

    txtNamaKeperluan.setText("");
    txtJumlah.setText("");
    txtHarga.setText("");
    txtKeterangan.setText("");
    rbBarangDagang.setSelected(false);
    rbOperasional.setSelected(false);
    kodeProdukDipilih = null;   
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah2ActionPerformed
    if (txtNamaKeperluan.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama item belum diisi!");
        return;
    }
    
    if (jDateChooser1.getDate() == null) {
    JOptionPane.showMessageDialog(this,
        "Tanggal pembelian wajib diisi",
        "Validasi",
        JOptionPane.WARNING_MESSAGE);
    return;
}

    if (txtJumlah.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Jumlah belum diisi!");
        return;
    }
    if (txtHarga.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harga belum diisi!");
        return;
    }

    // --- Jenis pengeluaran (pakai Radio Button) ---
    String jenisPengeluaran = "";
    if (rbBarangDagang.isSelected()) jenisPengeluaran = "Barang Dagang";
    else if (rbOperasional.isSelected()) jenisPengeluaran = "Operasional";
    else {
        JOptionPane.showMessageDialog(this, "Pilih jenis pengeluaran!");
        return;
    }

    // --- Pastikan ID Pembelian hanya dibuat sekali ---
    if (idPembelianGlobal == null || idPembelianGlobal.isEmpty()) {
        idPembelianGlobal = serv.generateIdPembelian();
    }

   
    // --- Ambil input user ---
    String namaItem = txtNamaKeperluan.getText();
    int jumlah;
    BigDecimal harga;

    try {
        jumlah = Integer.parseInt(txtJumlah.getText());
        harga = new BigDecimal(txtHarga.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Jumlah atau harga tidak valid!");
        return;
    }

    // --- Ambil Kode Produk dari Lookup ---
   String kodeProduk = kodeProdukDipilih; // BIARKAN NULL


    String keterangan = txtKeterangan.getText();

    if (rowYangDipilih == -1) {

        // ===== MODE TAMBAH =====
      if (counterDetail == -1) {
    String lastId = serv.generateIdDetail(); // contoh: DJ0001
    counterDetail = Integer.parseInt(lastId.substring(2)) - 1;
}

counterDetail++;
String idDetail = String.format("DJ%04d", counterDetail);

    Date tgl = jDateChooser1.getDate();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String tanggal = sdf.format(tgl);


modelDetail.addRow(new Object[]{
    tanggal,
    idDetail,
    idPembelianGlobal,
    namaItem,
    jumlah,
    harga,
    kodeProduk,
    jenisPengeluaran,
    keterangan
});


} else {
        Date tgl = jDateChooser1.getDate();
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String tanggal = sdf.format(tgl);
    // --- MODE EDIT (update baris yang dipilih) ---
    modelDetail.setValueAt(tanggal, rowYangDipilih, 0);
    modelDetail.setValueAt(namaItem, rowYangDipilih, 3);
    modelDetail.setValueAt(jumlah, rowYangDipilih, 4);
    modelDetail.setValueAt(harga, rowYangDipilih, 5);
    modelDetail.setValueAt(kodeProduk, rowYangDipilih, 6);
    modelDetail.setValueAt(jenisPengeluaran, rowYangDipilih, 7);
    modelDetail.setValueAt(keterangan, rowYangDipilih, 8);

    // Reset kembali ke mode tambah
    rowYangDipilih = -1;
}

    hitungTotal();
    
    txtNamaKeperluan.setText("");
    txtJumlah.setText("");
    txtHarga.setText("");
    txtKeterangan.setText("");
    rbBarangDagang.setSelected(false);
    rbOperasional.setSelected(false);
    kodeProdukDipilih = null;
    
    }//GEN-LAST:event_btnTambah2ActionPerformed

    private void txtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
   // validasi tabel
    if (tblPembelian.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Tidak ada data untuk disimpan");
        return;
    }

    // validasi tanggal
    if (jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Tanggal pembelian wajib diisi");
        return;
    }

    // validasi total
    if (txtTotal.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Total belum dihitung");
        return;
    }

    BigDecimal total = new BigDecimal(txtTotal.getText());

    // ambil tanggal manual
    java.util.Date tgl = jDateChooser1.getDate();
    java.sql.Date sqlDate = new java.sql.Date(tgl.getTime());

    // 1. insert pembelian (HEADER)
    pembelianServ pembServ = new pembelianServ();
    if (!pembServ.insertPembelian(idPembelianGlobal, sqlDate, total)) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan pembelian");
        return;
    }

    // 2. ambil detail dari JTable
    ArrayList<detail_pembelian> list = new ArrayList<>();
    DefaultTableModel model = (DefaultTableModel) tblPembelian.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        detail_pembelian dp = new detail_pembelian();

        dp.setId_detail(model.getValueAt(i, 1).toString());
        dp.setId_pembelian(idPembelianGlobal);
        dp.setNama_item(model.getValueAt(i, 3).toString());
        dp.setJumlah(Integer.parseInt(model.getValueAt(i, 4).toString()));
        dp.setHarga(new BigDecimal(model.getValueAt(i, 5).toString()));

        // kode produk (boleh null untuk operasional)
        Object valKode = model.getValueAt(i, 6);
        String kodeProduk = (valKode == null || valKode.toString().trim().isEmpty())
                ? null
                : valKode.toString();
        dp.setKode_produk(kodeProduk); // 🔴 INI TADI BELUM ADA

        // jenis pengeluaran (ENUM)
        dp.setJenis_pengeluaran(
                model.getValueAt(i, 7).toString().trim().toUpperCase()
        );

        // keterangan (boleh kosong)
        Object ket = model.getValueAt(i, 8);
        dp.setKeterangan(ket == null ? null : ket.toString());

        list.add(dp);
    }

    // 3. insert detail (BATCH)
    if (serv.insertBatch(list)) {
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

        model.setRowCount(0);
        txtTotal.setText("");
        jDateChooser1.setDate(null);
        kondisiAwal(); // generate idPembelianGlobal baru
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        FormDashboard dash = new FormDashboard();
        dash.setVisible(true);
        this.dispose(); // tutup form sekarang
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        FormDataProduk dash = new FormDataProduk();
        dash.setVisible(true);
        this.dispose(); // tutup form sekarang
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        FormPenjualan dash = new FormPenjualan();
        dash.setVisible(true);
        this.dispose(); // tutup form sekarang
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        FormPembelian dash = new FormPembelian();
        dash.setVisible(true);
        this.dispose(); // tutup form sekarang
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        FormRekap dash = new FormRekap();
        dash.setVisible(true);
        this.dispose(); // tutup form sekarang
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            FormLogin login = new FormLogin();
            login.setVisible(true);
            this.dispose(); // tutup form sekarang
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void BtnLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLookupActionPerformed
        // TODO add your handling code here:
        FormLookup lookup = new FormLookup();
    lookup.setTitle("DATA BARANG");
    lookup.jTable1.setModel(produkModel());
    lookup.setModal(true);
    lookup.setVisible(true);

    // setelah popup ditutup, kamu bisa ambil kodeProdukDipilih
    String kode = FormLookup.kodeProdukDipilih;
    System.out.println("Produk yang dipilih: " + kode);
    }//GEN-LAST:event_BtnLookupActionPerformed

    private void tblPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembelianMouseClicked
     rowYangDipilih = tblPembelian.getSelectedRow();

    if (rowYangDipilih == -1) return;

    txtNamaKeperluan.setText(modelDetail.getValueAt(rowYangDipilih, 3).toString());
    txtJumlah.setText(modelDetail.getValueAt(rowYangDipilih, 4).toString());
    txtHarga.setText(modelDetail.getValueAt(rowYangDipilih, 5).toString());
    txtKeterangan.setText(modelDetail.getValueAt(rowYangDipilih, 8).toString());

    // Jenis pengeluaran
    String jenis = modelDetail.getValueAt(rowYangDipilih, 7).toString();
    if (jenis.equals("Barang Dagang"))
        rbBarangDagang.setSelected(true);
    else
        rbOperasional.setSelected(true);

    // Kode produk dari tabel
    kodeProdukDipilih = modelDetail.getValueAt(rowYangDipilih, 6).toString();
    }//GEN-LAST:event_tblPembelianMouseClicked

    public DefaultTableModel produkModel() {
         String[] judul = {"Kode Barang", "Nama Barang"};

    ArrayList<produk> list = aserv.getListProduk();   // ganti var

    ArrayList<Object[]> barangOnly = new ArrayList<>();

    for (produk p : list) {                           // ganti var
        if (p.getKodeProduk().startsWith("B")) {
            barangOnly.add(new Object[]{
                p.getKodeProduk(),
                p.getNamaProduk()
            });
        }
    }

    Object[][] data = barangOnly.toArray(new Object[barangOnly.size()][]);

    return new DefaultTableModel(data, judul);
    }
    
     private void kondisiAwal() {
         
         idPembelianGlobal = serv.generateIdPembelian(); 
        txtNamaKeperluan.setEditable(false);
        txtSubtotal.setEditable(false);
        BtnLookup.setEnabled(false);

        rbBarangDagang.addActionListener(e -> aturMode());
        rbOperasional.addActionListener(e -> aturMode());

        txtJumlah.getDocument().addDocumentListener(new kalkulasiSubtotal());
        txtHarga.getDocument().addDocumentListener(new kalkulasiSubtotal());
    }

    private void aturMode() {
        if (rbBarangDagang.isSelected()) {
            BtnLookup.setEnabled(true);
            txtNamaKeperluan.setEditable(false);
            txtNamaKeperluan.setText("");
        } else if (rbOperasional.isSelected()) {
            BtnLookup.setEnabled(false);
            txtNamaKeperluan.setEditable(true);
            txtNamaKeperluan.setText("");
        }
    }
    
    private class kalkulasiSubtotal implements javax.swing.event.DocumentListener {

        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) { hitung(); }
        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) { hitung(); }
        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) { hitung(); }

        private void hitung() {
            try {
                int jml = Integer.parseInt(txtJumlah.getText());
                int hrg = Integer.parseInt(txtHarga.getText());
                txtSubtotal.setText(String.valueOf(jml * hrg));
            } catch (Exception ex) {
                txtSubtotal.setText("0");
            }
        }
    }
    
  



   private void hitungTotal() {
    DefaultTableModel model = (DefaultTableModel) tblPembelian.getModel();
    BigDecimal total = BigDecimal.ZERO;

    for (int i = 0; i < model.getRowCount(); i++) {
        Object val = model.getValueAt(i, 5); // kolom subtotal

        if (val instanceof BigDecimal) {
            total = total.add((BigDecimal) val);
        } else if (val != null) {
            // kalau disimpan sebagai string
            total = total.add(new BigDecimal(val.toString()));
        }
    }

    txtTotal.setText(total.toString());
}
   
  
   
   DefaultTableModel modelDetail;

private void initTable() {
    modelDetail = new DefaultTableModel();

    modelDetail.addColumn("Tanggal");
    modelDetail.addColumn("ID Detail");
    modelDetail.addColumn("ID Pembelian");
    modelDetail.addColumn("Nama Item");
    modelDetail.addColumn("Jumlah");
    modelDetail.addColumn("Subtotal");
    modelDetail.addColumn("Kode Produk");
    modelDetail.addColumn("Jenis Pengeluaran");
    modelDetail.addColumn("Keterangan");

    tblPembelian.setModel(modelDetail);
}




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BtnLookup;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JButton btnTambah2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbBarangDagang;
    private javax.swing.JRadioButton rbOperasional;
    private javax.swing.JTable tblPembelian;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKeterangan;
    public static javax.swing.JTextField txtNamaKeperluan;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
